// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	ControlMessage
	MapMessage
	ReduceMessage
*/
package message

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type ControlMessage_MessageType int32

const (
	ControlMessage_TypeEnd   ControlMessage_MessageType = 0
	ControlMessage_TypeBegin ControlMessage_MessageType = 1
)

var ControlMessage_MessageType_name = map[int32]string{
	0: "TypeEnd",
	1: "TypeBegin",
}
var ControlMessage_MessageType_value = map[string]int32{
	"TypeEnd":   0,
	"TypeBegin": 1,
}

func (x ControlMessage_MessageType) Enum() *ControlMessage_MessageType {
	p := new(ControlMessage_MessageType)
	*p = x
	return p
}
func (x ControlMessage_MessageType) String() string {
	return proto.EnumName(ControlMessage_MessageType_name, int32(x))
}
func (x *ControlMessage_MessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ControlMessage_MessageType_value, data, "ControlMessage_MessageType")
	if err != nil {
		return err
	}
	*x = ControlMessage_MessageType(value)
	return nil
}

type ControlMessage struct {
	Type             *ControlMessage_MessageType `protobuf:"varint,1,req,name=type,enum=message.ControlMessage_MessageType" json:"type,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *ControlMessage) Reset()         { *m = ControlMessage{} }
func (m *ControlMessage) String() string { return proto.CompactTextString(m) }
func (*ControlMessage) ProtoMessage()    {}

func (m *ControlMessage) GetType() ControlMessage_MessageType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ControlMessage_TypeEnd
}

type MapMessage struct {
	Key              []byte `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Data             []byte `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MapMessage) Reset()         { *m = MapMessage{} }
func (m *MapMessage) String() string { return proto.CompactTextString(m) }
func (*MapMessage) ProtoMessage()    {}

func (m *MapMessage) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *MapMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ReduceMessage struct {
	Key              []byte   `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Data             [][]byte `protobuf:"bytes,2,rep,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ReduceMessage) Reset()         { *m = ReduceMessage{} }
func (m *ReduceMessage) String() string { return proto.CompactTextString(m) }
func (*ReduceMessage) ProtoMessage()    {}

func (m *ReduceMessage) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ReduceMessage) GetData() [][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("message.ControlMessage_MessageType", ControlMessage_MessageType_name, ControlMessage_MessageType_value)
}
